### ISSUE TITLE
When EnableResponseLogging option enabled, multipart/form-data requests with files dumps binary data in console

### ISSUE THREAD

**Issue by crankedapps** [proudmonkey/AutoWrapper#37]
When submitting request data using multipart/form-data, the automatic logging feature dumps the entire binary contents of the files being uploaded into the logger/console.  I tried using AutoWrapIgnore attribute and the logging still persists.  I would love if logging was disabled when AutoWrapIgnore attribute is being used on a controller method or possibly adding another attribute that disables logging for specific controller method.  This would also be useful when trying to hide requests with sensitive information (ex: authentication endpoints with passwords) from the logger.

**Comment by proudmonkey** [comment]
Hi @crankedapps ,

Thank you for your suggestion. You've made a very valid point. I've released an RC version to include this feature. Please try to test it out on your end. Here's the version: https://www.nuget.org/packages/AutoWrapper.Core/4.1.0-rc

Sample Usage:

Using `[AutoWrapIgnore]` and setting `ShouldLogResponse` property to false:

```csharp
[HttpGet]
[AutoWrapIgnore(ShouldLogResponse = false)]
public async Task<IEnumerable<PersonResponse>> Get()
{
     // Rest of the code here
}
```

Or using the `[ResponseLogIgnore]` attribute:

```csharp
[HttpGet]
[ResponseLogIgnore]
public async Task<IEnumerable<PersonResponse>> Get()
{
     // Rest of the code here
}
```

Let me know your test results so I can release a new version with this updated. Thank you, once again! :)

**Comment by crankedapps** [comment]
Thank you, working perfectly!

**Comment by crankedapps** [comment]
Actually, I just noticed the [ResponseLogIgnore] does not work if you throw an ApiException, the request data can still be seen in the logger in this case (it's hidden if ApiResponse is returned though).  Additionally, in most cases I still like to automatically log that the endpoint was hit, I just want the actual request data hidden.  Is it possible to add a [ResponseLogHideRequestData] attribute or something?

**Comment by proudmonkey** [comment]
That's seems expected since the `[ResponseLogIgnore]` only handles the request/response data logging. Logging exceptions were different. You can disable it by setting `EnableExceptionLogging` to `false`.  Anyway, I'll consider implementing your request because it make sense for some scenarios :)

**Comment by crankedapps** [comment]
It is logging both the exception + request/response data when [ResponseLogIgnore] is used and ApiException is thrown.  So consider this scenerio: a user enters an invalid password, you throw an ApiException to tell the user they have invalid username/password combination, you will still see the user's password attempt in the logger which in my opinion still exposes sensitive information (ex: say that user accidentally entered their banking password vs password for your site by mistake).  I am requesting the exception still be logged as expected but the request JSON should not be logged when [ResponseLogIgnore] attribute is applied.

**Comment by proudmonkey** [comment]
`[ResponseLogIgnore] ` should not log request/response data.  But it will log the exceptions/error being thrown. I will do some test scenarios to over this.

**Comment by proudmonkey** [comment]
@crankedapps 

I've released a new RC version for this update here: https://www.nuget.org/packages/AutoWrapper.Core/4.1.0-rc2

Updated Sample Usage:

Sample Usage:

Using `[AutoWrapIgnore]` and setting `ShouldLogRequestData` property to false:

```csharp
[HttpGet]
[AutoWrapIgnore(ShouldLogRequestData = false)]
public async Task<IEnumerable<PersonResponse>> Get()
{
     // Rest of the code here
}
```

Or using the `[RequestDataLogIgnore]` attribute:

```csharp
[HttpGet]
[RequestDataLogIgnore]
public async Task<ApiResponse> Post([FromBody] CreatePersonRequest personRequest)
{
    if (!ModelState.IsValid)
    {
        throw new ApiException(ModelState.AllErrors());
    }
    return new ApiResponse("Record successfully created.", 
                            await _repo.CreateAsync(personRequest), 
                            Status201Created);
}
```

Let me know your thoughts. Thank you once again!

**Comment by crankedapps** [comment]
Everything is working great on my end, thank you very much for your attention on this!

**Comment by proudmonkey** [comment]
Awesome!. I'll release an official version after testing some more scenarios.
